[package]
name = "linux-3-finger-drag"
version = "0.1.0"
authors = ["Martin Reid <lmreid1997@gmail.com"]
edition = "2021"

[dependencies]
regex = "1.11.1"
input-linux = "0.7.1"
nix = "0.29.0"
signal-hook = "0.3.17"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
